# Generated by Zack and GPT 

def get_valid_number(prompt):
    """
    Prompt the user to enter a number (int or float).
    Validates the input and keeps asking until a valid number is provided.
    
    Parameters:
    prompt (str): The message to display to the user.

    Returns:
    float or int: The validated number input by the user.
    """
    is_valid = False
    while is_valid is not True:
        user_input = input(prompt)
        try:
            # Try to convert the input to a float
            number = float(user_input)
            
            # Check if the number is actually an integer
            if number.is_integer():
                return int(number)
            else:
                return number
        except ValueError:
            # If conversion fails, inform the user and prompt again
            print("Invalid input. Please enter a valid number.")


def get_yes_or_no(prompt):
    """
    Prompt the user to enter a Yes or No response.
    Validates the input and keeps asking until a valid response is provided.
    
    Parameters:
    prompt (str): The message to display to the user.

    Returns:
    bool: True if the user entered a Yes response, False if No.
    """
    while True:
        user_input = input(prompt).strip().lower()
        
        # Handle all valid Yes responses
        if user_input in ['yes', 'y', 'yeah', 'yep', 'sure', 'ok', 'true']:
            return True
        
        # Handle all valid No responses
        elif user_input in ['no', 'n', 'nope', 'nah', 'false']:
            return False
        
        # If input is invalid, inform the user and prompt again
        else:
            print("Invalid input. Please enter 'Yes' or 'No'.")


if __name__ == '__main__':
    # Example usage
    if get_yes_or_no("Do you want to continue? (yes/no): ") is True:
        print("Continuing...")
        # Example usage
        number = get_valid_number("Please enter a number (int or float): ")
        print(f"You entered: {number} (type: {type(number)})")
    else:
        print("Exiting... Goodbye")
